# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19a0016e2601fa0932e8beb0d6b92fff0646649249163dbe11befa8ee8ef4e6b4e52a71007efb1a4f536ff8e8203243f5fd1cc57695883c1975cf7abf906b92a

test:
  secret_key_base: 7b0aba30dcc5466a3245f12bd1bfc85839b5f83c23979eb93eef868f7ac1320c10288ade0001538036fbc4fe8c0524661f33973856c2ad99d4fb3b1c61a92db4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
